name: TepakapPlugin
version: '${project.version}'
main: fr.sny1411.tepakap.Main
api-version: 1.19
authors: [ sny1411 ]
commands:
  lock:
    description: permet de proteger un coffre
  unlock:
    description: permet de ne plus proteger un coffre
  admin:
    description: permet d'executer des commandes admin
